version: 1
disable_existing_loggers: false
formatters:
  simple:
    format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"

handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG  # Définir le niveau de log à DEBUG
    formatter: simple
    stream: ext://sys.stdout

loggers:
  rasa:
    level: DEBUG
    handlers: [console]
    propagate: no

  # Si vous avez des actions personnalisées :
  rasa.core.actions:
    level: DEBUG
    handlers: [console]
    propagate: no

root:
  level: INFO
  handlers: [console]
