name: Train Rasa Model

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  train:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Check HFTransformersNLP
        run: |
          pip show rasa transformers sentencepiece
          python -c "import rasa; print('Rasa version:', rasa.__version__)"
          python -c "from rasa.core.agent import Agent; print('Core OK')"  # Vérifie le module core
          python -c "from rasa.nlu.model import Interpreter; print('NLU OK')"  # Vérifie NLU
          python -c "from rasa.engine.recipes.default_recipe import DefaultV1Recipe; print('Recipe OK')"
          python -c "import transformers; print('Transformers OK')"

      - name: Train Rasa model
        run: |
          rasa train --domain models/domain.yml --data models/nlu.yml models/stories.yml

      - name: Upload trained model
        uses: actions/upload-artifact@v4
        with:
          name: rasa-model
          path: models/*.tar.gz

