name: Train Rasa Model

on:
  push:
    branches:
      - main  # ou la branche que tu veux utiliser pour déclencher le workflow
  workflow_dispatch:  # Cette ligne permet d'exécuter manuellement le workflow depuis GitHub

jobs:
  train:
    runs-on: ubuntu-latest  # Utilise un serveur Ubuntu pour exécuter le workflow

    steps:
      # 1. Vérifier le code source du repository
      - name: Checkout code
        uses: actions/checkout@v2

      # 2. Installer Python
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.9'

      # 3. Installer les dépendances nécessaires
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install rasa

      # 4. Entraîner le modèle Rasa
      - name: Train Rasa model
        run: |
          rasa train

      # 5. Télécharger le modèle généré comme un artifact
      - name: Upload trained model
        uses: actions/upload-artifact@v3
        with:
          name: rasa-model
          path: models/*.tar.gz  # Remplace avec le chemin de ton modèle Rasa
