name: Train Rasa Model

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: write  # Autorise l'écriture dans le dépôt

jobs:
  train:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Check dependencies
        run: |
          pip show rasa transformers sentencepiece
          python -c "import rasa; print('Rasa version:', rasa.__version__)"
          python -c "from rasa.core.agent import Agent; print('Core OK')"

      - name: Train Rasa model
         run: |
           mkdir -p /tmp/rasa_model_output
           rasa train --config config.yml --domain models/domain.yml --data models/nlu.yml models/stories.yml --out /tmp/rasa_model_output
           ls -lh /tmp/rasa_model_output || echo "Aucun fichier généré dans /tmp/rasa_model_output"
           # Trouver le fichier .tar.gz généré (il aura un nom comme 20250309-130158-excited-analogy.tar.gz)
           MODEL_FILE=$(ls /tmp/rasa_model_output/*.tar.gz | head -n 1)
              if [ -f "$MODEL_FILE" ]; then
                echo "Fichier modèle trouvé : $MODEL_FILE"
                  mkdir -p models
                   mv "$MODEL_FILE" models/model.tar.gz
              ls -lh models/model.tar.gz || echo "Erreur lors du déplacement du modèle"
                else
                  echo "Erreur : Aucun fichier .tar.gz trouvé dans /tmp/rasa_model_output"
                   exit 1
                       fi

      - name: Commit trained model
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          if [ -f models/model.tar.gz ]; then
            git add -f models/model.tar.gz
            git commit -m "Ajout du modèle entraîné" || echo "No changes to commit"
            git push origin main
          else
            echo "Erreur : model.tar.gz n'a pas été généré. Vérifiez les logs précédents."
            exit 1
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload trained model
        uses: actions/upload-artifact@v4
        with:
          name: rasa-model
          path: models/model.tar.gz
